# Generated by Django 5.0 on 2024-12-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anonymousmessage',
            old_name='OwnwerUsername',
            new_name='OwnerUsername',
        ),
    ]
