# Generated by Django 5.0 on 2024-12-05 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_ownwerusername_anonymousmessage_ownerusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerUsername', models.CharField(max_length=255)),
            ],
        ),
    ]
