# Generated by Django 5.0 on 2024-12-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_profile_bio_alter_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_link',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
