# Generated by Django 5.0 on 2024-12-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_profile_facebook_link_profile_instagram_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='facebook_link',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram_link',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='twitter_link',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
