# Generated by Django 5.0 on 2024-12-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_profile_facebook_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='sta.jpg', null=True, upload_to='ProfileImage'),
        ),
    ]
