# Generated by Django 5.0 on 2024-12-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousmessage',
            name='make_private',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
