# Generated by Django 5.0 on 2025-01-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_poll_user_alter_option_poll_alter_poll_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='option',
        ),
        migrations.AddField(
            model_name='poll',
            name='option_text',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='votes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
