# Generated by Django 5.0 on 2025-01-09 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_remove_vote_option_poll_option_text_poll_votes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='option_text',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='votes',
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=255, null=True)),
                ('votes', models.IntegerField(default=0, null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='App.poll')),
            ],
        ),
    ]
