# Generated by Django 5.0 on 2025-02-12 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_remove_poll_option_text_remove_poll_votes_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.option')),
            ],
        ),
    ]
