# Generated by Django 5.0 on 2025-02-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_messageslike'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageslike',
            name='no_of_likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='messageslike',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='messageslike',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
