# Generated by Django 5.0 on 2025-02-18 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_messageslike_no_of_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageslike',
            name='no_of_likes',
        ),
        migrations.AddField(
            model_name='anonymousmessage',
            name='no_of_likes',
            field=models.IntegerField(null=True),
        ),
    ]
