# Generated by Django 5.0 on 2025-02-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_remove_messageslike_no_of_likes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousmessage',
            name='no_of_likes',
            field=models.IntegerField(default=0),
        ),
    ]
