# Generated by Django 5.0 on 2025-02-18 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_alter_anonymousmessage_no_of_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageslike',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.anonymousmessage'),
        ),
    ]
