# Generated by Django 5.0 on 2025-02-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0022_alter_messageslike_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageslike',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
