# Generated by Django 5.0 on 2025-02-19 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0023_alter_messageslike_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
